version: "3.9" # optional since v1.27.0
services:
  redis:
    ports:
      - "6379:6379"
    image: redis

  # django-backend:
  #   build: ./django-backend
  #   # command: ["python ./src/manage.py runserver 0.0.0.0:8000"]
  #   command: "python ./src/manage.py runserver 0.0.0.0:8000"

  #   volumes:
  #     - ./django-backend/src:/project/src
  #   ports:
  #     - "8000:8000"

  fastapi-backend:
    build: ./fastapi-backend
    command: "uvicorn src.main:root --port 7609 --host 0.0.0.0 --reload"
    volumes:
      - ./fastapi-backend/src:/project/src
    ports:
      - 7609:7609

  nest-backend:
    build: ./nest-backend
    command: "yarn start:dev"
    volumes:
      - ./nest-backend/src:/project/src
    ports:
      - 3001:3001

  react-frontend:
    build: ./react-frontend
    command: "yarn start"
    # command: "ls"
    volumes:
      - ./react-frontend/src:/project/src
    ports:
      - 3000:3000
    environment:
      CHOKIDAR_USEPOLLING: "true"
      NODE_ENV: development

  nginx:
    build: ./nginx
    ports:
      - 8080:8080
      - 8081:8081
    restart: always
    depends_on:
      - fastapi-backend
      # - react-frontend

  telegram-bot:
    build: ./telegram-bot
    command: "yarn dev"
    volumes:
      - ./telegram-bot/src:/project/src
