version: "3.9" # optional since v1.27.0
services:
  fastapi-backend:
    build: ./fastapi-backend
    command: "python src/run.py"
    ports:
      - 5000:5000
    environment:
      MODE: prod

  nest-backend:
    build:
      context: ./nest-backend
      dockerfile: ./Dockerfile
      target: prod
    ports:
      - "${NEST_BACKEND_PORT}:3001"
    environment:
      MONGO_USER: "${MONGO_ROOT_USER}"
      MONGO_PASSWORD: "${MONGO_ROOT_PASSWORD}"
      MONGO_PORT: 27017
      MONGO_HOST: mongo
      TOKEN_SECRET: "${JWT_TOKEN_SECRET}"
    depends_on:
      - mongo

  react-frontend:
    build:
      context: ./react-frontend
      dockerfile: ./Dockerfile
      target: prod
    ports:
      - 3000:80
  nginx:
    build: ./nginx
    ports:
      - 80:8080
      # - 8081:8081
    restart: always
    environment:
      REACT_FRONTEND_HOST: react-frontend
      REACT_FRONTEND_PORT: "${REACT_FRONTEND_PORT}"
      NEST_BACKEND_HOST: nest-backend
      NEST_BACKEND_PORT: "${NEST_BACKEND_PORT}"
      FASTAPI_BACKEND_HOST: fastapi-backend
      FASTAPI_BACKEND_PORT: "${FASTAPI_BACKEND_PORT}"

    depends_on:
      - nest-backend
      - react-frontend
      - fastapi-backend

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_ROOT_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_ROOT_PASSWORD}"
    ports:
      - "${MONGO_PORT}:27017"
  # telegram-bot:
  #   build: ./telegram-bot
  #   command: "yarn dev"
  #   volumes:
  #     - ./telegram-bot/src:/project/src
  #   environment:
  #     TOKEN: "${TELEGRAM_BOT_TOKEN}"

