version: "3.9" # optional since v1.27.0
services:
  fastapi-backend:
    build: 
      context: ./fastapi-backend
      dockerfile: ./Dockerfile
      target: build
    command: "python src/run.py"
    ports:
      - 5000:5000
    environment:
      MODE: dev

  nest-backend:
    build:
      context: ./nest-backend
      dockerfile: ./Dockerfile
      target: prod
    ports:
      - "${NEST_BACKEND_PORT}:3001"
    environment:
      MONGO_USER: "${MONGO_ROOT_USER}"
      MONGO_PASSWORD: "${MONGO_ROOT_PASSWORD}"
      MONGO_PORT: "27017"
      MONGO_HOST: "mongo"
      TOKEN_SECRET: "${JWT_TOKEN_SECRET}"

  react-frontend:
    build:
      context: ./react-frontend
      dockerfile: ./Dockerfile.prod
    ports:
      - 3000:80
  nginx:
    build: ./nginx
    ports:
      - 80:8080
      # - 8081:8081
    restart: always
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_ROOT_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_ROOT_PASSWORD}"
    ports:
      - "${MONGO_PORT}:27017"
  # telegram-bot:
  #   build: ./telegram-bot
  #   command: "yarn dev"
  #   volumes:
  #     - ./telegram-bot/src:/project/src
  #   environment:
  #     TOKEN: "${TELEGRAM_BOT_TOKEN}"

