version: "3.9" # optional since v1.27.0
services:
  nest-backend:
    build:
      context: ./nest-backend
      dockerfile: Dockerfile
      target: build
    command: "yarn start:dev"
    volumes:
      - ./nest-backend/src:/app/src
    ports:
      - 3001:3001
    environment:
      MONGO_USER: "${MONGO_ROOT_USER}"
      MONGO_PASSWORD: "${MONGO_ROOT_PASSWORD}"
      MONGO_PORT: 27019
      MONGO_HOST: host.docker.internal
      TOKEN_SECRET: "${JWT_TOKEN_SECRET}"
    depends_on:
      - mongo
  nginx:
    build: ./nginx
    ports:
      - 9000:8080
      - 9001:8081
    environment:
      REACT_FRONTEND_HOST: host.docker.internal
      REACT_FRONTEND_PORT: 3000
      NEST_BACKEND_HOST: c78c-95-105-125-66.eu.ngrok.io
      NEST_BACKEND_PORT: 80
      FASTAPI_BACKEND_HOST: host.docker.internal
      FASTAPI_BACKEND_PORT: 5000
    restart: always
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_ROOT_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_ROOT_PASSWORD}"
    ports:
      - "${MONGO_PORT}:27017"
