version: "3.9" # optional since v1.27.0
services:
  # redis:
  #   ports:
  #     - "6379:6379"
  #   image: redis

  # fastapi-backend:
  #   build: ./fastapi-backend
  #   command: "uvicorn src.main:root --port 7609 --host 0.0.0.0 --reload"
  #   volumes:
  #     - ./fastapi-backend/src:/project/src
  #   ports:
  #     - 7609:7609

  nest-backend:
    build: ./nest-backend
    command: "yarn start:dev"
    volumes:
      - ./nest-backend/src:/project/src
    ports:
      - 3001:3001

  react-frontend:
    build: ./react-frontend
    command: "yarn start"
    # command: "ls"
    volumes:
      - ./react-frontend/src:/project/src
    ports:
      - 3000:3000

  nginx:
    build: ./nginx
    ports:
      - 8080:8080
      - 8081:8081
    environment:
      REACT_FRONTEND_HOST: host.docker.internal
      REACT_FRONTEND_PORT: 3000
      NEST_BACKEND_HOST: 62.113.104.153
      NEST_BACKEND_PORT: 3001
      FASTAPI_BACKEND_HOST: host.docker.internal
      FASTAPI_BACKEND_PORT: 5000

    restart: always

  telegram-bot:
    build: ./telegram-bot
    command: "yarn dev"
    volumes:
      - ./telegram-bot/src:/project/src
    environment:
      TOKEN: "${TELEGRAM_BOT_TOKEN}"

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_ROOT_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_ROOT_PASSWORD}"
    ports:
      - "${MONGO_PORT}:27017"
